intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

if($config.sparrow.use_date_polyfill)
{
  import intf_libs += date%lib{date date-tz}
}


lib{sparrow}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{sparrow}:
{
  cxx.export.poptions += "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs += $intf_libs
}

if($config.sparrow.use_date_polyfill)
{
  lib{sparrow}:
  {
    cxx.export.poptions += -DSPARROW_USE_DATE_POLYFILL
  }
}

# metadata (provided to users)
lib{sparrow}:
{
  export.metadata = 1 sparrow

  sparrow.use_date_polyfill = [bool] $config.sparrow.use_date_polyfill
}

# Install into the sparrow/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
